server:
  port: 3032
spring:
  application:
    name: inventory-service
  jpa:
    show-sql: true
    database: mysql
    generate-ddl: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inventory
    username: root
    password: tomriddle
#  flyway:
#    url: jdbc:mysql://localhost:3306/inventory
#    user: root
#    password: tomriddle
#    default-schema: inventory
#    create-schemas: true

